# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4928edbe1ada556f76b2fade5f3c40cd94f321b775d1e41270bbd5308a3c6e46ca125c093cc9c36482ba710723464e0f83cfc781b7d47b1c210aae3f34fd8b6d

test:
  secret_key_base: 50193eb05e7f55c0ddb6bcc38a3884f9ef1628d8f47b2a3bbfcac4494ffd171c5e3ac50a2978b0afd30b09834b636a2aad2476e7f4a468a0e2134c462abb0467

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
